version: '3.8'

services:
  bot:
    build: .
    container_name: anonim_voting_bot
    restart: always
    volumes:
      - ./voting.db:/app/voting.db
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
